<?php 
/**
 * @author VIJAYAKUMAR S
 * @copyright Copyright (c) 2017
 * @package Learn_Cloudflare
 */
?>

<div class="pp-buttons-container">
    <button class="action-default scalable save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" type="button" id="<?php echo $block->getId() ?>_flushcache" onclick="<?php echo $block->getOnclick(); ?>">
        <span><span><span><?php echo $block->escapeHtml($block->getButtonLabel()); ?></span></span></span>
    </button>
</div>